### ISSUE TITLE
Create new section for documentation

### ISSUE THREAD

**Issue by xabier** [decidim/decidim.org#43]
Create a new section on top menu that links to our documentation system or links to a file with a list of existing documentation.

**Comment by xabier** [comment]
The content for this section should be manually editable to include:
* Manuals and Texts:
   * Functionalities and Roadmap
   * Admin Manual
* Talks (slides and video)
   * Introduction to Decidim
   * How Decidim Works
   * Etc.

**Comment by andreslucena** [comment]
I'm assigning this to @zuzust because he'll be doing the GitBook integration and repositories (Manuals and Texts). 

Regarding Slides and Videos, can we upload them to this issue? 

Some Videos that I found on YouTube, we need to choose which ones we'll have (with english subtitles): 

https://www.youtube.com/watch?v=5qjpC62o8vs
https://www.youtube.com/watch?v=Q1DLCYg86Es
https://www.youtube.com/watch?v=zQYvdwGsg8M
https://www.youtube.com/watch?v=HBq8G1Ky53w
https://www.youtube.com/watch?v=9YVU9avRA28

LAB Metadecidim (playlist) 
https://www.youtube.com/playlist?list=PLGqsHW77DVq_98DB5w2owG1XEhGPSnZyM

**Comment by htmlboy** [comment]
OK, please let me know when the integration is done and I'll update the navigation.

**Comment by xabier** [comment]
If we can't make the integration, right now a simple list of documents with link to the PDF will do. I don't think we are going to have the doc system ready for Tuesday. This is why I requested the new section. I can update the content myself.

**Comment by xabier** [comment]
@htmlboy @zuzust can we create a new section docs that points to docs.decidim.org?

**Comment by xabier** [comment]
Or... actually better, right now, while we have docs.decidim.org almost empty, just create the section without content and we shall add there a link to our only properly built doc (features) and also some embeeded talks (video) and slides. Maybe also some content from the press. Simplest MVP a list of links

**Comment by xabier** [comment]
@htmlboy is there any mayor obstacle to do this before the JAM17 meeting? 

This would help us announce the official doc process that is already up and running at. For instance here:
https://docs.decidim.org/features/en/

**Comment by htmlboy** [comment]
PR ready: https://github.com/decidim/decidim.org/pull/75

**Comment by xabier** [comment]
@htmlboy your PR included Docs in navigation but pointing to a site whose links where broken. I accepted your PR and now I have created the page with content in  #77
