### ISSUE TITLE
Insert video(s) on home page

### ISSUE THREAD

**Issue by xabier** [decidim/decidim.org#61]
We have a number of powerfull videos to share, it would be good to have some room on the home page to display them. Either one video or more.

**Comment by andreslucena** [comment]
Do we have the URLs of any of those videos?

**Comment by xabier** [comment]
Yes:
In Spanish (and I would upload this to the catalan version as well): https://www.youtube.com/watch?v=zvYXzTOu2tY
In English: https://www.youtube.com/watch?v=qrQ8ij4Ekag

This are long videos. A shorter video explaining the platform with screenshots is coming soon (we need to wait for Juanli)

**Comment by xabier** [comment]
@htmlboy we already have the new video, it would be nice to have this feature. Can we have it?

**Comment by htmlboy** [comment]
@xabier Hi! In which section of the home page were you thinking to add this video?

**Comment by xabier** [comment]
I leave that decision in your hands @htmlboy :smiley: I think it is a good idea tu substitute the main image of the front page (right now the decidim.barcelona portal image) with the video, provided that we have a nice capture of the video (not sure how much this can be controlled), it will depend on the Youtube configuration.

**Comment by xabier** [comment]
@htmlboy we already have the video, we need to work out on the capture

**Comment by xabier** [comment]
also... for each language we need to put the link to youtube with the subtitles that correspond to that language

**Comment by htmlboy** [comment]
@xabier I think there are 2 problems with using this video instead of the main image:

- The image explains directly (and without the need of playing a video, which is not always an option) the purpose of the software

- The video is quite long (2h), and its main purpose is not to introduce the project, but to give a deep explanation. It probably belongs to another space… maybe in the features page?

**Comment by xabier** [comment]
@htmlboy the new video es 2min lenght, here is the link: https://www.youtube.com/watch?v=ahVZLOlE3GE have a look

**Comment by htmlboy** [comment]
@xabier oh, this is completely different! Are there different videos for the 3 languages?

**Comment by xabier** [comment]
No yet, but there will be, right now we have the video that
automatically triggers english subtitles.

**Comment by andreslucena** [comment]
At the moment we can put the video for the 3 languages as the same (so it's cleaner to change later).

**Comment by htmlboy** [comment]
OK! (sorry it took a bit to answer, busy days)

So what we could do is select a frame from the video, use it as a cover image (instead of the current one) and place a play button on top (that would launch the video in a modal box).

Sounds good? Could you provide a video frame (a quick screenshot + the video time so I can create one hi-res myself)?

Cheers!

**Comment by xabier** [comment]
@htmlboy take the current image (the front page of decidim.barcelona) instead of a frame, because there isn't really any frame that suits us.

**Comment by htmlboy** [comment]
Solved in https://github.com/decidim/decidim.org/pull/92

Translation files have the Youtube embed url (so you can change them with each translated version).

Cheers!
